spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:mysql://localhost:3306/baoleme?useSSL=false&serverTimezone=UTC
    username: root
    password: wqy20050308
    driver-class-name: com.mysql.cj.jdbc.Driver